apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application.yaml: |
    spring:
      cloud:
        gateway:
          routes:
            - id: auth-service
              uri: http://auth-service:8100
              predicates:
                - Path=/auth-service/**
            - id: orders-service
              uri: http://orders-service:8200
              predicates:
                - Path=/orders-service/**
            - id: catalog-service
              uri: http://catalog-service:8001
              predicates:
                - Path=/catalog-service/**

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: komendakacper123/api-gateway
          ports:
            - containerPort: 8765
          volumeMounts:
            - name: config-volume
              mountPath: /config
              subPath: application.yaml
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"  # W razie potrzeby możesz dodać aktywację profilu
      volumes:
        - name: config-volume
          configMap:
            name: api-gateway-config

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8765
      nodePort: 30080
  type: NodePort
