apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: shop.local
      http:
        paths:
          # Przekierowanie dla katalogu
          - path: /catalog(/|$)(api/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: catalog-service
                port:
                  number: 8001

          # Przekierowanie dla auth
          - path: /auth(/|$)(api/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 8100

          # Przekierowanie dla orders (płatności)
          - path: /orders(/|$)(api/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: orders-service
                port:
                  number: 8200
