apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: komendakacper123/catalog-service
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3307"
            - name: DB_USER
              value: "springstudent"
            - name: DB_PASSWORD
              value: "springstudent"
            - name: DB_NAME
              value: "clothing_store"
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
