apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: komendakacper123/orders-service
          env:
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: VAULT_TOKEN
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3307"
            - name: DB_USER
              value: "springstudent"
            - name: DB_PASSWORD
              value: "springstudent"
            - name: DB_NAME
              value: "clothing_store"
            - name: STRIPE_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STRIPE_KEY_SECRET
          ports:
            - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders-service
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
