version: '3.8'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
      MYSQL_DATABASE: clothing_store
      MYSQL_ROOT_PASSWORD: springstudent
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

  springboot-app:
    container_name: catalog-service
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - mysql
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysql:3306/clothing_store
      - spring.datasource.username=springstudent
      - spring.datasource.password=springstudent
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge
